# Generated by Django 3.2.7 on 2021-09-21 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
    ]
